### ISSUE TITLE
F-Droid Release

### ISSUE THREAD

**Issue by TheRouce** [Mailfence/mailfence-android#2]
Is there an F-Droid release planned? Also, when is the code going to be released?

**Comment by Mailfence** [comment]
Dear,

Please see this KB entry : https://kb.mailfence.com/kb/mailfence-app/

Regards,
The support

Le 11 nov. 2023 à 23:15, TheRouce ***@***.***> a écrit :

Is there an F-Droid release planned? Also, when is the code going to be released?

**Comment by TheRouce** [comment]
I'm specifically asking when the app will be made open source, not how I can install it

**Comment by Mailfence** [comment]
Dear,

We are progressing on this topic.
We expect to do it once it's fully developped (calendars, docs, contacts
still eed to be added)

No ETA yet known but it will happen ;-)

Regards,
Alan

Le 12 nov. 2023 à 08:46, TheRouce ***@***.***> a écrit :

I'm specifically asking when the app will be made open source, not how I can install it
