### ISSUE TITLE
Notifications issue for spam folder

### ISSUE THREAD

**Issue by wimb0** [Mailfence/mailfence-android#4]
Notifications in version 1.2.0 are sent for all folders and subfolders.
For example: I get a lot of notifications for new email in the spam folder.

To solve this, an option to change the notifications to only Inbox or something would be nice.
Currently there are 2 notification "channels" on android, maybe this can be added there?

**Comment by Mailfence** [comment]
Hello,

We will pass this to the dev team.

Thanks for your suggestion.

Regards,
Alan
Support

Le 10 janv. 2024 à 13:11, wimb0 ***@***.***> a écrit :

Notifications in version 1.2.0 are sent for all folders and subfolders.
For example: I get a lot of notifications for new email in the spam folder.
To solve this, an option to change the notifications to only Inbox or something would be nice.
Currently there are 2 notification "channels" on android, maybe this can be added there?

**Comment by Mailfence** [comment]
This problem was fixed in our backend a few weeks ago.
