### ISSUE TITLE
Feature request: mail signing

### ISSUE THREAD

**Issue by rtenberge** [Mailfence/mailfence-android#5]
Currently I'm using K9 as the Firefox web app installer wasn't working all too well on my GrapheneOS Pixel 7, same with Thunderbird: lots of double emails and sync errors. You can imagine I was very happy to see you now offer an apk wrapped version I can download right from your repository. 

There's one feature I'm missing right now though: being able to sign my emails with PGP. If that were implemented, I'd drop K9 right away.

**Comment by Mailfence** [comment]
Hello,

This feature will probably be available in the next release, due in 4 weeks approx.

Regards,
The support

Le 15 févr. 2024 à 15:48, Robin ***@***.***> a écrit :

Currently I'm using K9 as the Firefox web app installer wasn't working all too well on my GrapheneOS Pixel 7, same with Thunderbird: lots of double emails and sync errors. You can imagine I was very happy to see you now offer an apk wrapped version I can download right from your repository.
There's one feature I'm missing right now though: being able to sign my emails with PGP. If that were implemented, I'd drop K9 right away.

**Comment by Mailfence** [comment]
Hello,
The version 1.3.0 now allows you to sign your emails with PGP.
Regards
